/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 7
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 11
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym__ws = 1,
  anon_sym_LBRACE = 2,
  anon_sym_RBRACE = 3,
  anon_sym_DOLLARPRE = 4,
  anon_sym_DOLLARRETRY = 5,
  anon_sym_DOLLARASSERT = 6,
  anon_sym_DOLLARPOST = 7,
  anon_sym_DOLLAR = 8,
  aux_sym_directive_token1 = 9,
  aux_sym_request_line_token1 = 10,
  aux_sym_request_line_token2 = 11,
  sym_method_chunk = 12,
  sym_url_chunk = 13,
  sym_proto_chunk = 14,
  aux_sym_header_line_token1 = 15,
  anon_sym_COLON = 16,
  sym_header_name_chunk = 17,
  sym_header_value_chunk = 18,
  sym_dynamic_chunk = 19,
  sym_body_chunk = 20,
  sym_raw_lua_content = 21,
  sym_source_file = 22,
  sym_lifecycle_script = 23,
  sym_lifecycle_directive = 24,
  sym_inline_script = 25,
  sym_directive = 26,
  sym_request_line = 27,
  sym_method = 28,
  sym_url = 29,
  sym_proto = 30,
  sym_header_line = 31,
  sym_header_name = 32,
  sym_header_value = 33,
  sym_dynamic_header = 34,
  sym_body = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_source_file_repeat2 = 37,
  aux_sym_method_repeat1 = 38,
  aux_sym_url_repeat1 = 39,
  aux_sym_proto_repeat1 = 40,
  aux_sym_header_name_repeat1 = 41,
  aux_sym_header_value_repeat1 = 42,
  aux_sym_dynamic_header_repeat1 = 43,
  aux_sym_body_repeat1 = 44,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym__ws] = "_ws",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_DOLLARPRE] = "$PRE",
  [anon_sym_DOLLARRETRY] = "$RETRY",
  [anon_sym_DOLLARASSERT] = "$ASSERT",
  [anon_sym_DOLLARPOST] = "$POST",
  [anon_sym_DOLLAR] = "$",
  [aux_sym_directive_token1] = "directive_token1",
  [aux_sym_request_line_token1] = "request_line_token1",
  [aux_sym_request_line_token2] = "request_line_token2",
  [sym_method_chunk] = "method_chunk",
  [sym_url_chunk] = "url_chunk",
  [sym_proto_chunk] = "proto_chunk",
  [aux_sym_header_line_token1] = "header_line_token1",
  [anon_sym_COLON] = ":",
  [sym_header_name_chunk] = "header_name_chunk",
  [sym_header_value_chunk] = "header_value_chunk",
  [sym_dynamic_chunk] = "dynamic_chunk",
  [sym_body_chunk] = "body_chunk",
  [sym_raw_lua_content] = "raw_lua_content",
  [sym_source_file] = "source_file",
  [sym_lifecycle_script] = "lifecycle_script",
  [sym_lifecycle_directive] = "lifecycle_directive",
  [sym_inline_script] = "inline_script",
  [sym_directive] = "directive",
  [sym_request_line] = "request_line",
  [sym_method] = "method",
  [sym_url] = "url",
  [sym_proto] = "proto",
  [sym_header_line] = "header_line",
  [sym_header_name] = "header_name",
  [sym_header_value] = "header_value",
  [sym_dynamic_header] = "dynamic_header",
  [sym_body] = "body",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_source_file_repeat2] = "source_file_repeat2",
  [aux_sym_method_repeat1] = "method_repeat1",
  [aux_sym_url_repeat1] = "url_repeat1",
  [aux_sym_proto_repeat1] = "proto_repeat1",
  [aux_sym_header_name_repeat1] = "header_name_repeat1",
  [aux_sym_header_value_repeat1] = "header_value_repeat1",
  [aux_sym_dynamic_header_repeat1] = "dynamic_header_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym__ws] = sym__ws,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_DOLLARPRE] = anon_sym_DOLLARPRE,
  [anon_sym_DOLLARRETRY] = anon_sym_DOLLARRETRY,
  [anon_sym_DOLLARASSERT] = anon_sym_DOLLARASSERT,
  [anon_sym_DOLLARPOST] = anon_sym_DOLLARPOST,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [aux_sym_directive_token1] = aux_sym_directive_token1,
  [aux_sym_request_line_token1] = aux_sym_request_line_token1,
  [aux_sym_request_line_token2] = aux_sym_request_line_token2,
  [sym_method_chunk] = sym_method_chunk,
  [sym_url_chunk] = sym_url_chunk,
  [sym_proto_chunk] = sym_proto_chunk,
  [aux_sym_header_line_token1] = aux_sym_header_line_token1,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_header_name_chunk] = sym_header_name_chunk,
  [sym_header_value_chunk] = sym_header_value_chunk,
  [sym_dynamic_chunk] = sym_dynamic_chunk,
  [sym_body_chunk] = sym_body_chunk,
  [sym_raw_lua_content] = sym_raw_lua_content,
  [sym_source_file] = sym_source_file,
  [sym_lifecycle_script] = sym_lifecycle_script,
  [sym_lifecycle_directive] = sym_lifecycle_directive,
  [sym_inline_script] = sym_inline_script,
  [sym_directive] = sym_directive,
  [sym_request_line] = sym_request_line,
  [sym_method] = sym_method,
  [sym_url] = sym_url,
  [sym_proto] = sym_proto,
  [sym_header_line] = sym_header_line,
  [sym_header_name] = sym_header_name,
  [sym_header_value] = sym_header_value,
  [sym_dynamic_header] = sym_dynamic_header,
  [sym_body] = sym_body,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_source_file_repeat2] = aux_sym_source_file_repeat2,
  [aux_sym_method_repeat1] = aux_sym_method_repeat1,
  [aux_sym_url_repeat1] = aux_sym_url_repeat1,
  [aux_sym_proto_repeat1] = aux_sym_proto_repeat1,
  [aux_sym_header_name_repeat1] = aux_sym_header_name_repeat1,
  [aux_sym_header_value_repeat1] = aux_sym_header_value_repeat1,
  [aux_sym_dynamic_header_repeat1] = aux_sym_dynamic_header_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLARPRE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLARRETRY] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLARASSERT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLARPOST] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_directive_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_line_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_request_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_method_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_url_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_proto_chunk] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_header_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_header_name_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_body_chunk] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_lua_content] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_lifecycle_script] = {
    .visible = true,
    .named = true,
  },
  [sym_lifecycle_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_inline_script] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym_request_line] = {
    .visible = true,
    .named = true,
  },
  [sym_method] = {
    .visible = true,
    .named = true,
  },
  [sym_url] = {
    .visible = true,
    .named = true,
  },
  [sym_proto] = {
    .visible = true,
    .named = true,
  },
  [sym_header_line] = {
    .visible = true,
    .named = true,
  },
  [sym_header_name] = {
    .visible = true,
    .named = true,
  },
  [sym_header_value] = {
    .visible = true,
    .named = true,
  },
  [sym_dynamic_header] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_source_file_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_method_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_url_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_proto_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_name_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_header_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dynamic_header_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_directive = 1,
  field_dynamic = 2,
  field_lua_code = 3,
  field_method = 4,
  field_name = 5,
  field_proto = 6,
  field_url = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_directive] = "directive",
  [field_dynamic] = "dynamic",
  [field_lua_code] = "lua_code",
  [field_method] = "method",
  [field_name] = "name",
  [field_proto] = "proto",
  [field_url] = "url",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 1},
  [6] = {.index = 7, .length = 2},
  [7] = {.index = 9, .length = 2},
  [8] = {.index = 11, .length = 2},
  [9] = {.index = 13, .length = 3},
  [10] = {.index = 16, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_dynamic, 0},
  [1] =
    {field_directive, 0},
    {field_lua_code, 2},
  [3] =
    {field_name, 0},
  [4] =
    {field_method, 0},
    {field_url, 2},
  [6] =
    {field_name, 1},
  [7] =
    {field_name, 0},
    {field_value, 2},
  [9] =
    {field_name, 1},
    {field_value, 3},
  [11] =
    {field_name, 0},
    {field_value, 3},
  [13] =
    {field_method, 0},
    {field_proto, 4},
    {field_url, 2},
  [16] =
    {field_name, 1},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 36,
  [68] = 68,
  [69] = 69,
  [70] = 36,
  [71] = 36,
  [72] = 72,
  [73] = 36,
  [74] = 36,
  [75] = 36,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 77,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 82,
  [95] = 82,
  [96] = 82,
  [97] = 82,
  [98] = 82,
  [99] = 82,
  [100] = 77,
  [101] = 101,
  [102] = 77,
  [103] = 77,
  [104] = 77,
  [105] = 77,
  [106] = 92,
  [107] = 92,
  [108] = 92,
  [109] = 92,
  [110] = 92,
  [111] = 92,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(13);
      ADVANCE_MAP(
        '\t', 15,
        '\n', 16,
        '\r', 14,
        ' ', 15,
        '$', 24,
        '-', 49,
        ':', 48,
        '{', 18,
        '}', 19,
        '.', 45,
        '/', 45,
      );
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(40);
      if (lookahead == '$') ADVANCE(25);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(40);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(44);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == ':') ADVANCE(48);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      if (lookahead != 0) ADVANCE(52);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(25);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != ':') ADVANCE(52);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0) ADVANCE(51);
      END_STATE();
    case 9:
      if (lookahead == '$') ADVANCE(25);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 10:
      if (eof) ADVANCE(13);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      if (lookahead != 0 &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(52);
      END_STATE();
    case 11:
      if (eof) ADVANCE(13);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 12:
      if (eof) ADVANCE(13);
      if (lookahead == '$') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(15);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(53);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOLLARPRE);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOLLARRETRY);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_DOLLARASSERT);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_DOLLARPOST);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (lookahead == 'A') ADVANCE(32);
      if (lookahead == 'P') ADVANCE(29);
      if (lookahead == 'R') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('B' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'E') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'E') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'E') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'O') ADVANCE(33);
      if (lookahead == 'R') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'R') ADVANCE(38);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'R') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'S') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'S') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'S') ADVANCE(28);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'T') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'T') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'T') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (lookahead == 'Y') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_directive_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_request_line_token1);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym_request_line_token2);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_method_chunk);
      if (lookahead == '-') ADVANCE(49);
      if (lookahead == '.' ||
          lookahead == '/') ADVANCE(45);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_method_chunk);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_url_chunk);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '$') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_proto_chunk);
      if (('.' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_header_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          lookahead != ':') ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_header_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$') ADVANCE(51);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_header_name_chunk);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_header_name_chunk);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          (lookahead < '0' || ':' < lookahead)) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_header_value_chunk);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_dynamic_chunk);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != '$' &&
          lookahead != ':') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_body_chunk);
      if (lookahead != 0 &&
          lookahead != '$') ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 10},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 10},
  [6] = {.lex_state = 10},
  [7] = {.lex_state = 10},
  [8] = {.lex_state = 10},
  [9] = {.lex_state = 11},
  [10] = {.lex_state = 11},
  [11] = {.lex_state = 11},
  [12] = {.lex_state = 12},
  [13] = {.lex_state = 12},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 11},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 10},
  [25] = {.lex_state = 10},
  [26] = {.lex_state = 10},
  [27] = {.lex_state = 11},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 11},
  [30] = {.lex_state = 11},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 11},
  [34] = {.lex_state = 11},
  [35] = {.lex_state = 11},
  [36] = {.lex_state = 12},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 8},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 11},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 7},
  [53] = {.lex_state = 7},
  [54] = {.lex_state = 7},
  [55] = {.lex_state = 3},
  [56] = {.lex_state = 8},
  [57] = {.lex_state = 4},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 6},
  [60] = {.lex_state = 8},
  [61] = {.lex_state = 6},
  [62] = {.lex_state = 4},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 6},
  [65] = {.lex_state = 4},
  [66] = {.lex_state = 7},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 9},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 3},
  [72] = {.lex_state = 5},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 8},
  [75] = {.lex_state = 6},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 0, .external_lex_state = 1},
  [78] = {.lex_state = 10},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 10},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0, .external_lex_state = 1},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 3},
  [86] = {.lex_state = 0, .external_lex_state = 1},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 10},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 10},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 10},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 0, .external_lex_state = 1},
  [101] = {.lex_state = 10},
  [102] = {.lex_state = 0, .external_lex_state = 1},
  [103] = {.lex_state = 0, .external_lex_state = 1},
  [104] = {.lex_state = 0, .external_lex_state = 1},
  [105] = {.lex_state = 0, .external_lex_state = 1},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_DOLLARPRE] = ACTIONS(1),
    [anon_sym_DOLLARRETRY] = ACTIONS(1),
    [anon_sym_DOLLARASSERT] = ACTIONS(1),
    [anon_sym_DOLLARPOST] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [aux_sym_directive_token1] = ACTIONS(1),
    [aux_sym_request_line_token1] = ACTIONS(1),
    [aux_sym_request_line_token2] = ACTIONS(1),
    [sym_method_chunk] = ACTIONS(1),
    [sym_proto_chunk] = ACTIONS(1),
    [aux_sym_header_line_token1] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_header_name_chunk] = ACTIONS(1),
    [sym_raw_lua_content] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(79),
    [sym_lifecycle_script] = STATE(33),
    [sym_lifecycle_directive] = STATE(88),
    [sym_inline_script] = STATE(69),
    [sym_directive] = STATE(92),
    [sym_request_line] = STATE(2),
    [sym_method] = STATE(85),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_method_repeat1] = STATE(63),
    [sym__ws] = ACTIONS(3),
    [anon_sym_DOLLARPRE] = ACTIONS(5),
    [anon_sym_DOLLARRETRY] = ACTIONS(5),
    [anon_sym_DOLLARASSERT] = ACTIONS(5),
    [anon_sym_DOLLARPOST] = ACTIONS(5),
    [anon_sym_DOLLAR] = ACTIONS(7),
    [aux_sym_directive_token1] = ACTIONS(7),
    [sym_method_chunk] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 17,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    STATE(29), 1,
      sym_body,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(41), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(5), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [57] = 17,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(35), 1,
      sym_body,
    STATE(49), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(6), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [114] = 17,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_body,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(38), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(7), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [171] = 17,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(35), 1,
      sym_body,
    STATE(49), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(8), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [228] = 17,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(30), 1,
      sym_body,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(38), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(8), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [285] = 17,
    ACTIONS(13), 1,
      aux_sym_request_line_token2,
    ACTIONS(15), 1,
      aux_sym_header_line_token1,
    ACTIONS(17), 1,
      sym_header_name_chunk,
    ACTIONS(19), 1,
      sym_dynamic_chunk,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(31), 1,
      sym_inline_script,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(34), 1,
      sym_body,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(8), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [342] = 12,
    ACTIONS(34), 1,
      aux_sym_header_line_token1,
    ACTIONS(37), 1,
      sym_header_name_chunk,
    ACTIONS(40), 1,
      sym_dynamic_chunk,
    STATE(31), 1,
      sym_inline_script,
    STATE(62), 1,
      aux_sym_header_name_repeat1,
    STATE(93), 1,
      sym_dynamic_header,
    STATE(106), 1,
      sym_directive,
    STATE(112), 1,
      sym_header_name,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(31), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(8), 2,
      sym_header_line,
      aux_sym_source_file_repeat2,
    ACTIONS(29), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [385] = 11,
    ACTIONS(9), 1,
      sym_method_chunk,
    STATE(3), 1,
      sym_request_line,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(63), 1,
      aux_sym_method_repeat1,
    STATE(69), 1,
      sym_inline_script,
    STATE(85), 1,
      sym_method,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(92), 1,
      sym_directive,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [423] = 11,
    ACTIONS(9), 1,
      sym_method_chunk,
    STATE(4), 1,
      sym_request_line,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(63), 1,
      aux_sym_method_repeat1,
    STATE(69), 1,
      sym_inline_script,
    STATE(85), 1,
      sym_method,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(92), 1,
      sym_directive,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [461] = 11,
    ACTIONS(9), 1,
      sym_method_chunk,
    STATE(3), 1,
      sym_request_line,
    STATE(10), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(63), 1,
      aux_sym_method_repeat1,
    STATE(69), 1,
      sym_inline_script,
    STATE(85), 1,
      sym_method,
    STATE(88), 1,
      sym_lifecycle_directive,
    STATE(92), 1,
      sym_directive,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    ACTIONS(5), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [499] = 6,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      sym_body_chunk,
    STATE(107), 1,
      sym_directive,
    ACTIONS(7), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(13), 2,
      sym_inline_script,
      aux_sym_body_repeat1,
    ACTIONS(45), 5,
      sym__ws,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [524] = 6,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(56), 1,
      sym_body_chunk,
    STATE(107), 1,
      sym_directive,
    ACTIONS(53), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    STATE(13), 2,
      sym_inline_script,
      aux_sym_body_repeat1,
    ACTIONS(51), 5,
      sym__ws,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [549] = 2,
    ACTIONS(59), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(61), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [565] = 6,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_method_chunk,
    ACTIONS(68), 2,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
    ACTIONS(65), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [589] = 2,
    ACTIONS(70), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(72), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [605] = 2,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(76), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [621] = 2,
    ACTIONS(78), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(80), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [637] = 2,
    ACTIONS(82), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(84), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [653] = 2,
    ACTIONS(86), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(88), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [669] = 2,
    ACTIONS(90), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(92), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [685] = 2,
    ACTIONS(94), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(96), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [701] = 2,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(100), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [717] = 2,
    ACTIONS(102), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(104), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [733] = 2,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(108), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [749] = 2,
    ACTIONS(110), 2,
      ts_builtin_sym_end,
      aux_sym_request_line_token2,
    ACTIONS(112), 9,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      aux_sym_header_line_token1,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [765] = 2,
    ACTIONS(114), 3,
      ts_builtin_sym_end,
      sym__ws,
      sym_method_chunk,
    ACTIONS(116), 6,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
  [779] = 8,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(120), 1,
      aux_sym_request_line_token2,
    ACTIONS(122), 1,
      aux_sym_header_line_token1,
    ACTIONS(124), 1,
      sym_header_value_chunk,
    STATE(78), 1,
      sym_header_value,
    STATE(110), 1,
      sym_directive,
    STATE(60), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [805] = 6,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(126), 1,
      sym__ws,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(49), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [827] = 6,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(130), 1,
      sym__ws,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [849] = 8,
    ACTIONS(132), 1,
      anon_sym_DOLLAR,
    ACTIONS(135), 1,
      aux_sym_directive_token1,
    ACTIONS(138), 1,
      aux_sym_request_line_token2,
    ACTIONS(140), 1,
      anon_sym_COLON,
    ACTIONS(142), 1,
      sym_header_name_chunk,
    ACTIONS(144), 1,
      sym_dynamic_chunk,
    STATE(108), 1,
      sym_directive,
    STATE(52), 2,
      sym_inline_script,
      aux_sym_dynamic_header_repeat1,
  [875] = 8,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(124), 1,
      sym_header_value_chunk,
    ACTIONS(146), 1,
      aux_sym_request_line_token2,
    ACTIONS(148), 1,
      aux_sym_header_line_token1,
    STATE(89), 1,
      sym_header_value,
    STATE(110), 1,
      sym_directive,
    STATE(60), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [901] = 3,
    ACTIONS(152), 1,
      sym__ws,
    ACTIONS(150), 2,
      ts_builtin_sym_end,
      sym_method_chunk,
    ACTIONS(154), 6,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
  [917] = 6,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    ACTIONS(158), 1,
      sym__ws,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(46), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [939] = 6,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(160), 1,
      sym__ws,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(38), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [961] = 2,
    ACTIONS(162), 1,
      ts_builtin_sym_end,
    ACTIONS(164), 8,
      sym__ws,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
      sym_body_chunk,
  [975] = 5,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(48), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [994] = 5,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1013] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(168), 1,
      sym_url_chunk,
    STATE(109), 1,
      sym_directive,
    ACTIONS(166), 2,
      aux_sym_request_line_token1,
      aux_sym_request_line_token2,
    STATE(44), 2,
      sym_inline_script,
      aux_sym_url_repeat1,
  [1034] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(38), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1053] = 5,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1072] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(170), 1,
      aux_sym_request_line_token2,
    ACTIONS(172), 1,
      sym_header_value_chunk,
    STATE(91), 1,
      sym_header_value,
    STATE(110), 1,
      sym_directive,
    STATE(60), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [1095] = 5,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(46), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1114] = 6,
    ACTIONS(174), 1,
      anon_sym_DOLLAR,
    ACTIONS(177), 1,
      aux_sym_directive_token1,
    ACTIONS(182), 1,
      sym_url_chunk,
    STATE(109), 1,
      sym_directive,
    ACTIONS(180), 2,
      aux_sym_request_line_token1,
      aux_sym_request_line_token2,
    STATE(44), 2,
      sym_inline_script,
      aux_sym_url_repeat1,
  [1135] = 7,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(172), 1,
      sym_header_value_chunk,
    ACTIONS(185), 1,
      aux_sym_request_line_token2,
    STATE(81), 1,
      sym_header_value,
    STATE(110), 1,
      sym_directive,
    STATE(60), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [1158] = 5,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1177] = 5,
    ACTIONS(187), 1,
      ts_builtin_sym_end,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(51), 1,
      aux_sym_source_file_repeat1,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1196] = 5,
    ACTIONS(156), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1215] = 5,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1234] = 2,
    ACTIONS(63), 2,
      ts_builtin_sym_end,
      sym_method_chunk,
    ACTIONS(68), 6,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
      anon_sym_DOLLAR,
      aux_sym_directive_token1,
  [1247] = 5,
    ACTIONS(189), 1,
      ts_builtin_sym_end,
    STATE(15), 1,
      aux_sym_source_file_repeat1,
    STATE(33), 1,
      sym_lifecycle_script,
    STATE(88), 1,
      sym_lifecycle_directive,
    ACTIONS(128), 4,
      anon_sym_DOLLARPRE,
      anon_sym_DOLLARRETRY,
      anon_sym_DOLLARASSERT,
      anon_sym_DOLLARPOST,
  [1266] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(191), 1,
      aux_sym_request_line_token2,
    ACTIONS(193), 1,
      sym_dynamic_chunk,
    STATE(108), 1,
      sym_directive,
    STATE(53), 2,
      sym_inline_script,
      aux_sym_dynamic_header_repeat1,
  [1286] = 6,
    ACTIONS(195), 1,
      anon_sym_DOLLAR,
    ACTIONS(198), 1,
      aux_sym_directive_token1,
    ACTIONS(201), 1,
      aux_sym_request_line_token2,
    ACTIONS(203), 1,
      sym_dynamic_chunk,
    STATE(108), 1,
      sym_directive,
    STATE(53), 2,
      sym_inline_script,
      aux_sym_dynamic_header_repeat1,
  [1306] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(193), 1,
      sym_dynamic_chunk,
    ACTIONS(206), 1,
      aux_sym_request_line_token2,
    STATE(108), 1,
      sym_directive,
    STATE(53), 2,
      sym_inline_script,
      aux_sym_dynamic_header_repeat1,
  [1326] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(208), 1,
      sym_url_chunk,
    STATE(76), 1,
      sym_url,
    STATE(109), 1,
      sym_directive,
    STATE(39), 2,
      sym_inline_script,
      aux_sym_url_repeat1,
  [1346] = 6,
    ACTIONS(210), 1,
      anon_sym_DOLLAR,
    ACTIONS(213), 1,
      aux_sym_directive_token1,
    ACTIONS(216), 1,
      aux_sym_request_line_token2,
    ACTIONS(218), 1,
      sym_header_value_chunk,
    STATE(110), 1,
      sym_directive,
    STATE(56), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [1366] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(221), 1,
      sym_header_name_chunk,
    STATE(84), 1,
      sym_header_name,
    STATE(106), 1,
      sym_directive,
    STATE(62), 2,
      sym_inline_script,
      aux_sym_header_name_repeat1,
  [1386] = 6,
    ACTIONS(223), 1,
      anon_sym_DOLLAR,
    ACTIONS(226), 1,
      aux_sym_directive_token1,
    ACTIONS(229), 1,
      aux_sym_request_line_token1,
    ACTIONS(231), 1,
      sym_method_chunk,
    STATE(92), 1,
      sym_directive,
    STATE(58), 2,
      sym_inline_script,
      aux_sym_method_repeat1,
  [1406] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(234), 1,
      aux_sym_request_line_token2,
    ACTIONS(236), 1,
      sym_proto_chunk,
    STATE(111), 1,
      sym_directive,
    STATE(64), 2,
      sym_inline_script,
      aux_sym_proto_repeat1,
  [1426] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(238), 1,
      aux_sym_request_line_token2,
    ACTIONS(240), 1,
      sym_header_value_chunk,
    STATE(110), 1,
      sym_directive,
    STATE(56), 2,
      sym_inline_script,
      aux_sym_header_value_repeat1,
  [1446] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(242), 1,
      sym_proto_chunk,
    STATE(101), 1,
      sym_proto,
    STATE(111), 1,
      sym_directive,
    STATE(59), 2,
      sym_inline_script,
      aux_sym_proto_repeat1,
  [1466] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(244), 1,
      anon_sym_COLON,
    ACTIONS(246), 1,
      sym_header_name_chunk,
    STATE(106), 1,
      sym_directive,
    STATE(65), 2,
      sym_inline_script,
      aux_sym_header_name_repeat1,
  [1486] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(248), 1,
      aux_sym_request_line_token1,
    ACTIONS(250), 1,
      sym_method_chunk,
    STATE(92), 1,
      sym_directive,
    STATE(58), 2,
      sym_inline_script,
      aux_sym_method_repeat1,
  [1506] = 6,
    ACTIONS(252), 1,
      anon_sym_DOLLAR,
    ACTIONS(255), 1,
      aux_sym_directive_token1,
    ACTIONS(258), 1,
      aux_sym_request_line_token2,
    ACTIONS(260), 1,
      sym_proto_chunk,
    STATE(111), 1,
      sym_directive,
    STATE(64), 2,
      sym_inline_script,
      aux_sym_proto_repeat1,
  [1526] = 6,
    ACTIONS(263), 1,
      anon_sym_DOLLAR,
    ACTIONS(266), 1,
      aux_sym_directive_token1,
    ACTIONS(269), 1,
      anon_sym_COLON,
    ACTIONS(271), 1,
      sym_header_name_chunk,
    STATE(106), 1,
      sym_directive,
    STATE(65), 2,
      sym_inline_script,
      aux_sym_header_name_repeat1,
  [1546] = 6,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(191), 1,
      aux_sym_request_line_token2,
    ACTIONS(274), 1,
      sym_dynamic_chunk,
    STATE(108), 1,
      sym_directive,
    STATE(54), 2,
      sym_inline_script,
      aux_sym_dynamic_header_repeat1,
  [1566] = 2,
    ACTIONS(162), 3,
      aux_sym_directive_token1,
      aux_sym_request_line_token2,
      anon_sym_COLON,
    ACTIONS(164), 3,
      anon_sym_DOLLAR,
      sym_header_name_chunk,
      sym_dynamic_chunk,
  [1577] = 5,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    ACTIONS(276), 1,
      sym_body_chunk,
    STATE(107), 1,
      sym_directive,
    STATE(12), 2,
      sym_inline_script,
      aux_sym_body_repeat1,
  [1594] = 3,
    ACTIONS(278), 1,
      anon_sym_DOLLAR,
    ACTIONS(282), 1,
      aux_sym_request_line_token2,
    ACTIONS(280), 3,
      aux_sym_directive_token1,
      aux_sym_request_line_token1,
      sym_method_chunk,
  [1606] = 2,
    ACTIONS(164), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 4,
      aux_sym_directive_token1,
      aux_sym_request_line_token1,
      aux_sym_request_line_token2,
      sym_method_chunk,
  [1616] = 2,
    ACTIONS(164), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 4,
      aux_sym_directive_token1,
      aux_sym_request_line_token1,
      aux_sym_request_line_token2,
      sym_url_chunk,
  [1626] = 4,
    ACTIONS(7), 1,
      anon_sym_DOLLAR,
    ACTIONS(118), 1,
      aux_sym_directive_token1,
    STATE(66), 1,
      sym_inline_script,
    STATE(108), 1,
      sym_directive,
  [1639] = 2,
    ACTIONS(164), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 3,
      aux_sym_directive_token1,
      aux_sym_request_line_token2,
      sym_dynamic_chunk,
  [1648] = 2,
    ACTIONS(164), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 3,
      aux_sym_directive_token1,
      aux_sym_request_line_token2,
      sym_header_value_chunk,
  [1657] = 2,
    ACTIONS(164), 1,
      anon_sym_DOLLAR,
    ACTIONS(162), 3,
      aux_sym_directive_token1,
      aux_sym_request_line_token2,
      sym_proto_chunk,
  [1666] = 2,
    ACTIONS(284), 1,
      aux_sym_request_line_token1,
    ACTIONS(286), 1,
      aux_sym_request_line_token2,
  [1673] = 1,
    ACTIONS(288), 1,
      sym_raw_lua_content,
  [1677] = 1,
    ACTIONS(290), 1,
      aux_sym_request_line_token2,
  [1681] = 1,
    ACTIONS(292), 1,
      ts_builtin_sym_end,
  [1685] = 1,
    ACTIONS(294), 1,
      anon_sym_RBRACE,
  [1689] = 1,
    ACTIONS(296), 1,
      aux_sym_request_line_token2,
  [1693] = 1,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
  [1697] = 1,
    ACTIONS(300), 1,
      sym_raw_lua_content,
  [1701] = 1,
    ACTIONS(302), 1,
      anon_sym_COLON,
  [1705] = 1,
    ACTIONS(304), 1,
      aux_sym_request_line_token1,
  [1709] = 1,
    ACTIONS(306), 1,
      sym_raw_lua_content,
  [1713] = 1,
    ACTIONS(308), 1,
      anon_sym_LBRACE,
  [1717] = 1,
    ACTIONS(310), 1,
      anon_sym_LBRACE,
  [1721] = 1,
    ACTIONS(312), 1,
      aux_sym_request_line_token2,
  [1725] = 1,
    ACTIONS(314), 1,
      anon_sym_LBRACE,
  [1729] = 1,
    ACTIONS(316), 1,
      aux_sym_request_line_token2,
  [1733] = 1,
    ACTIONS(318), 1,
      anon_sym_LBRACE,
  [1737] = 1,
    ACTIONS(320), 1,
      aux_sym_request_line_token2,
  [1741] = 1,
    ACTIONS(322), 1,
      anon_sym_RBRACE,
  [1745] = 1,
    ACTIONS(324), 1,
      anon_sym_RBRACE,
  [1749] = 1,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
  [1753] = 1,
    ACTIONS(328), 1,
      anon_sym_RBRACE,
  [1757] = 1,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
  [1761] = 1,
    ACTIONS(332), 1,
      anon_sym_RBRACE,
  [1765] = 1,
    ACTIONS(334), 1,
      sym_raw_lua_content,
  [1769] = 1,
    ACTIONS(336), 1,
      aux_sym_request_line_token2,
  [1773] = 1,
    ACTIONS(338), 1,
      sym_raw_lua_content,
  [1777] = 1,
    ACTIONS(340), 1,
      sym_raw_lua_content,
  [1781] = 1,
    ACTIONS(342), 1,
      sym_raw_lua_content,
  [1785] = 1,
    ACTIONS(344), 1,
      sym_raw_lua_content,
  [1789] = 1,
    ACTIONS(346), 1,
      anon_sym_LBRACE,
  [1793] = 1,
    ACTIONS(348), 1,
      anon_sym_LBRACE,
  [1797] = 1,
    ACTIONS(350), 1,
      anon_sym_LBRACE,
  [1801] = 1,
    ACTIONS(352), 1,
      anon_sym_LBRACE,
  [1805] = 1,
    ACTIONS(354), 1,
      anon_sym_LBRACE,
  [1809] = 1,
    ACTIONS(356), 1,
      anon_sym_LBRACE,
  [1813] = 1,
    ACTIONS(358), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 57,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 171,
  [SMALL_STATE(6)] = 228,
  [SMALL_STATE(7)] = 285,
  [SMALL_STATE(8)] = 342,
  [SMALL_STATE(9)] = 385,
  [SMALL_STATE(10)] = 423,
  [SMALL_STATE(11)] = 461,
  [SMALL_STATE(12)] = 499,
  [SMALL_STATE(13)] = 524,
  [SMALL_STATE(14)] = 549,
  [SMALL_STATE(15)] = 565,
  [SMALL_STATE(16)] = 589,
  [SMALL_STATE(17)] = 605,
  [SMALL_STATE(18)] = 621,
  [SMALL_STATE(19)] = 637,
  [SMALL_STATE(20)] = 653,
  [SMALL_STATE(21)] = 669,
  [SMALL_STATE(22)] = 685,
  [SMALL_STATE(23)] = 701,
  [SMALL_STATE(24)] = 717,
  [SMALL_STATE(25)] = 733,
  [SMALL_STATE(26)] = 749,
  [SMALL_STATE(27)] = 765,
  [SMALL_STATE(28)] = 779,
  [SMALL_STATE(29)] = 805,
  [SMALL_STATE(30)] = 827,
  [SMALL_STATE(31)] = 849,
  [SMALL_STATE(32)] = 875,
  [SMALL_STATE(33)] = 901,
  [SMALL_STATE(34)] = 917,
  [SMALL_STATE(35)] = 939,
  [SMALL_STATE(36)] = 961,
  [SMALL_STATE(37)] = 975,
  [SMALL_STATE(38)] = 994,
  [SMALL_STATE(39)] = 1013,
  [SMALL_STATE(40)] = 1034,
  [SMALL_STATE(41)] = 1053,
  [SMALL_STATE(42)] = 1072,
  [SMALL_STATE(43)] = 1095,
  [SMALL_STATE(44)] = 1114,
  [SMALL_STATE(45)] = 1135,
  [SMALL_STATE(46)] = 1158,
  [SMALL_STATE(47)] = 1177,
  [SMALL_STATE(48)] = 1196,
  [SMALL_STATE(49)] = 1215,
  [SMALL_STATE(50)] = 1234,
  [SMALL_STATE(51)] = 1247,
  [SMALL_STATE(52)] = 1266,
  [SMALL_STATE(53)] = 1286,
  [SMALL_STATE(54)] = 1306,
  [SMALL_STATE(55)] = 1326,
  [SMALL_STATE(56)] = 1346,
  [SMALL_STATE(57)] = 1366,
  [SMALL_STATE(58)] = 1386,
  [SMALL_STATE(59)] = 1406,
  [SMALL_STATE(60)] = 1426,
  [SMALL_STATE(61)] = 1446,
  [SMALL_STATE(62)] = 1466,
  [SMALL_STATE(63)] = 1486,
  [SMALL_STATE(64)] = 1506,
  [SMALL_STATE(65)] = 1526,
  [SMALL_STATE(66)] = 1546,
  [SMALL_STATE(67)] = 1566,
  [SMALL_STATE(68)] = 1577,
  [SMALL_STATE(69)] = 1594,
  [SMALL_STATE(70)] = 1606,
  [SMALL_STATE(71)] = 1616,
  [SMALL_STATE(72)] = 1626,
  [SMALL_STATE(73)] = 1639,
  [SMALL_STATE(74)] = 1648,
  [SMALL_STATE(75)] = 1657,
  [SMALL_STATE(76)] = 1666,
  [SMALL_STATE(77)] = 1673,
  [SMALL_STATE(78)] = 1677,
  [SMALL_STATE(79)] = 1681,
  [SMALL_STATE(80)] = 1685,
  [SMALL_STATE(81)] = 1689,
  [SMALL_STATE(82)] = 1693,
  [SMALL_STATE(83)] = 1697,
  [SMALL_STATE(84)] = 1701,
  [SMALL_STATE(85)] = 1705,
  [SMALL_STATE(86)] = 1709,
  [SMALL_STATE(87)] = 1713,
  [SMALL_STATE(88)] = 1717,
  [SMALL_STATE(89)] = 1721,
  [SMALL_STATE(90)] = 1725,
  [SMALL_STATE(91)] = 1729,
  [SMALL_STATE(92)] = 1733,
  [SMALL_STATE(93)] = 1737,
  [SMALL_STATE(94)] = 1741,
  [SMALL_STATE(95)] = 1745,
  [SMALL_STATE(96)] = 1749,
  [SMALL_STATE(97)] = 1753,
  [SMALL_STATE(98)] = 1757,
  [SMALL_STATE(99)] = 1761,
  [SMALL_STATE(100)] = 1765,
  [SMALL_STATE(101)] = 1769,
  [SMALL_STATE(102)] = 1773,
  [SMALL_STATE(103)] = 1777,
  [SMALL_STATE(104)] = 1781,
  [SMALL_STATE(105)] = 1785,
  [SMALL_STATE(106)] = 1789,
  [SMALL_STATE(107)] = 1793,
  [SMALL_STATE(108)] = 1797,
  [SMALL_STATE(109)] = 1801,
  [SMALL_STATE(110)] = 1805,
  [SMALL_STATE(111)] = 1809,
  [SMALL_STATE(112)] = 1813,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 4, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(90),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(57),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(62),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat2, 2, 0, 0), SHIFT_REPEAT(72),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 2, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 2, 0, 1),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 3, 1, 3),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 3, 1, 3),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 4, 0, 4),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 4, 0, 4),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 4, 1, 5),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 4, 1, 5),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 4, 1, 3),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 4, 1, 3),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 4, 1, 6),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 4, 1, 6),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 5, 1, 5),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 5, 1, 5),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 5, 1, 7),
  [100] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 5, 1, 7),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 5, 1, 8),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 5, 1, 8),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_request_line, 6, 0, 9),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_request_line, 6, 0, 9),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_line, 6, 1, 10),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_header_line, 6, 1, 10),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lifecycle_script, 4, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lifecycle_script, 4, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_name_repeat1, 1, 0, 0), SHIFT(90),
  [135] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_name_repeat1, 1, 0, 0), SHIFT(90),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_header, 1, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_name_repeat1, 1, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_header_name_repeat1, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 5, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_inline_script, 4, 0, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_inline_script, 4, 0, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_url, 1, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [177] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_url_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 6, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 7, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_header, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [195] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_dynamic_header_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [198] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dynamic_header_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dynamic_header_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dynamic_header_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dynamic_header, 3, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [210] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0),
  [218] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_value_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [223] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_method_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 2, 0, 0), SHIFT_REPEAT(58),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_proto, 1, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_value, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [244] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_name, 1, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [248] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_method, 1, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [252] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [255] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_proto_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [263] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_header_name_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_name_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_name_repeat1, 2, 0, 0),
  [271] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_name_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_method_repeat1, 1, 0, 0),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_method_repeat1, 1, 0, 0),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [292] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [308] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lifecycle_directive, 1, 0, 0),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [312] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [314] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_raw_lua_content = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_raw_lua_content] = sym_raw_lua_content,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_raw_lua_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_sinq_external_scanner_create(void);
void tree_sitter_sinq_external_scanner_destroy(void *);
bool tree_sitter_sinq_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_sinq_external_scanner_serialize(void *, char *);
void tree_sitter_sinq_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_sinq(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_sinq_external_scanner_create,
      tree_sitter_sinq_external_scanner_destroy,
      tree_sitter_sinq_external_scanner_scan,
      tree_sitter_sinq_external_scanner_serialize,
      tree_sitter_sinq_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "sinq",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
